spring:
  application:
    name: print-assistant
  thymeleaf:
    cache: false
    check-template: true
  redis:
    host: pass.moku.site
    database: 0
    port: 34567
    timeout: 120000

server:
  port: 8000
  tomcat:
    max-http-post-size: -1
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


print:
  history:
    expire:
      days: 7


